# Rename this file to languages.toml to enable multilingual support
[en]
languageName = "English"
languagedirection = "ltr"
title = "Phan Nhut Minh"
weight = 2
[vi]
languageName = "Tieng Viet"
languagedirection = "ltr"
title = "Phan Nhựt Minh"
weight = 1
