# Configure main menu and social menu
#[[main]]
#identifier = "home"
#name = "Home"
#url = "/"
#[main.params]
#icon = "home"
#newtab = true



[[social]]
identifier = "instagram"
name = "Instagram"
url = "https://www.instagram.com/phannhutminh1298"

[social.params]
icon = "brand-instagram"

[[social]]
identifier = "x"
name = "X"
url = "https://x.com/phan_minh94158"

[social.params]
icon = "brand-x"

[[social]]
identifier = "artstation"
name = "Artstation"
url = "https://www.artstation.com/phan-nhut-minh"

[social.params]
icon = "brand-artstation"

[[social]]
indentifier = "facebook"
name = "Facebook"
url = "https://www.facebook.com/phannhutminh1298"

[[social.params]]
icon = "brand-facebook"